name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_PACKAGE_TOKEN }}

    - name: Build Image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .
        
    - name: Push Image
      run: docker push ghcr.io/${{ github.repository }}:latest
